### ISSUE TITLE
Setup Firebase hosting

### ISSUE THREAD

**Issue by kiiiyo** [kiiiyo/kiiiyo-io#1]
# Overview

Setup Firebase hosting for kiiiyo io product.

## TODOs

- [x] Git Message `.gitmessage`
- [x] Git Ignore `.gitignore`
- [x] Setup Next.js 
- [x] Setup Firebase Hosting
